version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE_DATABASE=db.sqlite3
    volumes:
      - ./db.sqlite3:/db/db.sqlite3
